'use client';

import type { ApiResponse, UsageMetricsDto } from '@dmtecha/shared-types';
import { useEffect, useState, useCallback } from 'react';

const API_URL = process.env['NEXT_PUBLIC_API_URL'] ?? 'http://localhost:4000';

interface Props {
  accessToken: string;
}

export function UsageMetrics({ accessToken }: Props) {
  const [metrics, setMetrics] = useState<UsageMetricsDto | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const loadMetrics = useCallback(async () => {
    try {
      setLoading(true);
      setError('');
      const res = await fetch(`${API_URL}/chat/usage`, {
        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
      });
      const data = (await res.json()) as ApiResponse<UsageMetricsDto>;
      if (data.success && data.data) {
        setMetrics(data.data);
      } else {
        throw new Error(data.error?.message ?? 'Failed to load usage metrics');
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Something went wrong');
    } finally {
      setLoading(false);
    }
  }, [accessToken]);

  useEffect(() => {
    void loadMetrics();
  }, [loadMetrics]);

  if (loading) {
    return <div className="loading-state">Loading usage metrics...</div>;
  }

  if (error) {
    return (
      <div className="metrics-panel">
        <p className="error-message">{error}</p>
        <button className="btn-primary" onClick={() => void loadMetrics()}>Retry</button>
      </div>
    );
  }

  const tokenUsage = metrics || {
    totalTokens: 0,
    promptTokens: 0,
    completionTokens: 0,
    conversationCount: 0,
    messageCount: 0,
  };

  // Rough cost estimate based on OpenAI gpt-4o-mini rates ($0.15/1M prompt, $0.60/1M completion)
  const promptCost = (tokenUsage.promptTokens / 1000000) * 0.15;
  const completionCost = (tokenUsage.completionTokens / 1000000) * 0.60;
  const totalCost = promptCost + completionCost;

  return (
    <div className="metrics-panel">
      <div className="metrics-header">
        <h2>📊 AI Usage Metrics & Tokens Dashboard</h2>
        <button className="btn-ghost" onClick={() => void loadMetrics()}>🔄 Refresh</button>
      </div>

      <div className="metrics-grid">
        <div className="metric-card">
          <div className="metric-icon">🪙</div>
          <div className="metric-value">
            {tokenUsage.totalTokens.toLocaleString()}
          </div>
          <div className="metric-label">Total Tokens Consumed</div>
          <div className="metric-desc">Aggregate prompt + completion tokens</div>
        </div>

        <div className="metric-card">
          <div className="metric-icon">📥</div>
          <div className="metric-value text-accent">
            {tokenUsage.promptTokens.toLocaleString()}
          </div>
          <div className="metric-label">Prompt Tokens</div>
          <div className="metric-desc">Context injected + questions sent</div>
        </div>

        <div className="metric-card">
          <div className="metric-icon">📤</div>
          <div className="metric-value text-success">
            {tokenUsage.completionTokens.toLocaleString()}
          </div>
          <div className="metric-label">Completion Tokens</div>
          <div className="metric-desc">Tokens generated by AI responses</div>
        </div>

        <div className="metric-card">
          <div className="metric-icon">💸</div>
          <div className="metric-value">
            ${totalCost.toFixed(5)}
          </div>
          <div className="metric-label">Estimated Cost (USD)</div>
          <div className="metric-desc">Calculated at gpt-4o-mini rates</div>
        </div>
      </div>

      <div className="metrics-subgrid">
        <div className="metric-subcard">
          <h3>💬 Chat Footprint</h3>
          <div className="subcard-stat">
            <span className="stat-num">{tokenUsage.conversationCount}</span>
            <span className="stat-label">Conversations Started</span>
          </div>
          <div className="subcard-stat">
            <span className="stat-num">{tokenUsage.messageCount}</span>
            <span className="stat-label">Total Messages Exchanged</span>
          </div>
        </div>

        <div className="metric-subcard">
          <h3>💡 System Insights</h3>
          <div className="insight-row">
            <span className="insight-label">Avg. Tokens per Message</span>
            <span className="insight-value">
              {tokenUsage.messageCount > 0
                ? Math.round(tokenUsage.totalTokens / tokenUsage.messageCount).toLocaleString()
                : 0}
            </span>
          </div>
          <div className="insight-row">
            <span className="insight-label">Prompt vs. Completion Ratio</span>
            <span className="insight-value">
              {tokenUsage.totalTokens > 0
                ? `${Math.round((tokenUsage.promptTokens / tokenUsage.totalTokens) * 100)}% / ${Math.round((tokenUsage.completionTokens / tokenUsage.totalTokens) * 100)}%`
                : '0% / 0%'}
            </span>
          </div>
          <div className="insight-row">
            <span className="insight-label">Database Health</span>
            <span className="insight-value text-success">Online & Secure</span>
          </div>
        </div>
      </div>
    </div>
  );
}
